"""
finance_engine.py — Financial Engine
======================================

Computes complete P&L for every order row using all operational variables
generated by the other engines.

Generated columns
-----------------
cogs                      : Cost of Goods Sold (INR)
gross_profit              : Revenue − COGS
gross_margin_pct          : Gross profit as % of revenue
packaging_cost            : Box, poly-bag, label, fill (INR)
warehouse_handling_cost   : Pick-pack-sort cost per unit (INR)
inventory_holding_cost    : Monthly storage cost per order (INR)
platform_commission       : Amazon commission (INR)
payment_gateway_fee       : Payment processing fee (INR)
cancellation_cost         : Fee for cancelled orders (INR)
net_profit                : Full-stack profit after all costs (INR)
profit_margin_pct         : Net profit as % of revenue
profit_leakage            : Total cost deducted below gross margin (INR)

Why these columns don't exist in public datasets
-------------------------------------------------
Full-stack P&L is the most sensitive financial data a retailer holds.
Even publicly-listed companies do not share per-SKU or per-order P&L.
"""

import pandas as pd

from config import CFG, get_category_margin, get_platform_commission, get_packaging_cost


_WH_HANDLING = CFG["warehouse_handling_cost_per_unit"]
_HOLDING_PCT = CFG["inventory_holding_cost_pct"]
_HOLDING_MONTHS = CFG["inventory_holding_months"]
_GATEWAY_PCT = CFG["payment_gateway_fee_pct"]
_CANCEL_COST = CFG["cancellation_cost_flat"]


def run(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    revenue = df["Amount"].fillna(0)
    qty = df["Qty"].fillna(1).clip(lower=1)
    category = df["Category"]

    # ── COGS ──────────────────────────────────────────────────────────────────
    # Formula: COGS = Revenue × (1 − gross_margin)
    margin_pct = category.apply(get_category_margin)
    df["cogs"] = (revenue * (1 - margin_pct)).round(2)

    # ── Gross Profit ──────────────────────────────────────────────────────────
    df["gross_profit"] = (revenue - df["cogs"]).round(2)
    df["gross_margin_pct"] = (
        (df["gross_profit"] / revenue.replace(0, pd.NA)).fillna(0) * 100
    ).round(2)

    # ── Packaging Cost ────────────────────────────────────────────────────────
    # Formula: packaging_rate(category) × qty
    df["packaging_cost"] = (
        category.apply(get_packaging_cost) * qty
    ).round(2)

    # ── Warehouse Handling Cost ───────────────────────────────────────────────
    # Formula: fixed_cost_per_unit × qty
    df["warehouse_handling_cost"] = (_WH_HANDLING * qty).round(2)

    # ── Inventory Holding Cost ────────────────────────────────────────────────
    # Formula: COGS × holding_cost_pct × holding_months
    df["inventory_holding_cost"] = (
        df["cogs"] * _HOLDING_PCT * _HOLDING_MONTHS
    ).round(2)

    # ── Platform Commission ───────────────────────────────────────────────────
    # Formula: revenue × commission_rate(category)
    df["platform_commission"] = (
        revenue * category.apply(get_platform_commission)
    ).round(2)

    # ── Payment Gateway Fee ───────────────────────────────────────────────────
    # Formula: revenue × gateway_fee_pct
    df["payment_gateway_fee"] = (revenue * _GATEWAY_PCT).round(2)

    # ── Reverse Logistics Cost ────────────────────────────────────────────────
    # Only for returned/returning orders
    _REV_LOG_PCT = CFG["reverse_logistics_cost_pct"]
    shipping = df.get("shipping_cost", pd.Series(0.0, index=df.index)).fillna(0)
    returned_mask = df["Status"].str.contains("Return", na=False)
    df["reverse_logistics_cost"] = 0.0
    df.loc[returned_mask, "reverse_logistics_cost"] = (
        shipping[returned_mask] * _REV_LOG_PCT
    ).round(2)

    # ── Cancellation Cost ─────────────────────────────────────────────────────
    cancelled_mask = df["Status"].str.startswith("Cancelled", na=False)
    df["cancellation_cost"] = 0.0
    df.loc[cancelled_mask, "cancellation_cost"] = _CANCEL_COST

    # ── Marketing Attribution Cost ────────────────────────────────────────────
    # Already generated by marketing_engine — reuse if present
    mktg = df.get("marketing_attribution_cost", pd.Series(0.0, index=df.index)).fillna(0)

    # ── Return Cost (total) ───────────────────────────────────────────────────
    refund = df.get("refund_amount", pd.Series(0.0, index=df.index)).fillna(0)
    refurb = df.get("refurbishment_cost", pd.Series(0.0, index=df.index)).fillna(0)
    refund_proc = df.get("refund_processing_cost", pd.Series(0.0, index=df.index)).fillna(0)
    total_return_cost = refund + refurb + refund_proc

    # ── Net Profit ────────────────────────────────────────────────────────────
    # Formula:
    # Net Profit = Revenue
    #   - COGS
    #   - Packaging
    #   - Shipping
    #   - Fuel Surcharge
    #   - Shipping Insurance
    #   - Platform Commission
    #   - Payment Gateway Fee
    #   - Marketing Attribution
    #   - Return Costs
    #   - Reverse Logistics
    #   - Warehouse Handling
    #   - Inventory Holding
    #   - Cancellation Cost
    fuel = df.get("fuel_surcharge", pd.Series(0.0, index=df.index)).fillna(0)
    insurance = df.get("shipping_insurance", pd.Series(0.0, index=df.index)).fillna(0)

    df["net_profit"] = (
        revenue
        - df["cogs"]
        - df["packaging_cost"]
        - shipping
        - fuel
        - insurance
        - df["platform_commission"]
        - df["payment_gateway_fee"]
        - mktg
        - total_return_cost
        - df["reverse_logistics_cost"]
        - df["warehouse_handling_cost"]
        - df["inventory_holding_cost"]
        - df["cancellation_cost"]
    ).round(2)

    df["profit_margin_pct"] = (
        (df["net_profit"] / revenue.replace(0, pd.NA)).fillna(0) * 100
    ).round(2)

    # ── Profit Leakage ────────────────────────────────────────────────────────
    # Total costs below gross profit = where money leaks post-gross line
    df["profit_leakage"] = (df["gross_profit"] - df["net_profit"]).round(2)

    return df
