"""
analytics_agent.py — Agent for routing to existing analytics modules.
"""

from pathlib import Path
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import StrOutputParser

from llm import get_llm
from state import CopilotState
from logger import get_logger
from chart_builder import build_chart_from_df

# Import all analytics modules
import sys
# Add parent dir to path so analytics modules can be imported
sys.path.append(str(Path(__file__).parent.parent.parent))

from analytics import (
    profit_analysis,
    customer_analysis,
    product_analysis,
    inventory_analysis,
    marketing_analysis,
    returns_analysis,
    statistical_analysis
)

log = get_logger("analytics_agent")

_SUMMARY_PROMPT_TEMPLATE = """You are a senior business analyst.
I have run an automated analytics module on our data.
Here are the raw insights generated by the system:
{raw_insights}

Please write a concise (100-200 words) business summary for the user based on these insights.
Highlight the most important findings and recommendations. Do not use markdown like ```.

User Question: {question}
Summary:
"""

def route_module(question: str):
    """Determine which analytics module to run based on keywords."""
    from services.analytics_service import MODULE_REGISTRY
    q = question.lower()
    
    if any(kw in q for kw in ["profit", "margin", "leakage"]):
        return MODULE_REGISTRY["Profit Analysis"], "Profit Analysis"
    elif any(kw in q for kw in ["customer", "retention", "segment"]):
        return MODULE_REGISTRY["Customer Analysis"], "Customer Analysis"
    elif any(kw in q for kw in ["inventory", "warehouse", "stock"]):
        return MODULE_REGISTRY["Inventory Analysis"], "Inventory Analysis"
    elif any(kw in q for kw in ["campaign", "marketing", "roi"]):
        return MODULE_REGISTRY["Marketing Analysis"], "Marketing Analysis"
    elif any(kw in q for kw in ["return", "refund"]):
        return MODULE_REGISTRY["Returns Analysis"], "Returns Analysis"
    elif any(kw in q for kw in ["statistics", "trend", "correlation"]):
        return MODULE_REGISTRY["Statistical Analysis"], "Statistical Analysis"
    else:
        # Default
        return MODULE_REGISTRY["Product Analysis"], "Product Analysis"


def run_analytics_agent(state: CopilotState) -> CopilotState:
    """Run the chosen analytics module and summarize its insights."""
    log.info("Starting Analytics Agent pipeline...")
    question = state.get("question", "")
    
    if not question:
        state["error"] = "No question provided to analytics agent."
        state["business_summary"] = "I didn't receive a question."
        return state

    module_func, module_name = route_module(question)
    log.info(f"Routed to {module_name}")
    
    try:
        # Run the module with save_to_disk=False
        result = module_func(save_to_disk=False)
        
        # Read the generated insights from the structured result
        if isinstance(result, dict) and "insights_text" in result:
            raw_insights = result["insights_text"]
        else:
            raw_insights = str(result) if result else "No insights were generated."

        # Summarize with LLM
        llm = get_llm()
        prompt = PromptTemplate(
            input_variables=["raw_insights", "question"],
            template=_SUMMARY_PROMPT_TEMPLATE
        )
        chain = prompt | llm | StrOutputParser()
        
        summary = chain.invoke({
            "raw_insights": raw_insights,
            "question": question
        })
        
        state["business_summary"] = summary.strip()
        state["analytics_result"] = raw_insights

        # ── Build Chart (optional, never raises) ──────────────────────────────
        # Attempt to parse top-level insights dict into a plottable DataFrame
        try:
            if isinstance(result, dict):
                # Build a simple DataFrame from any dict with numeric values
                chart_data = {k: v for k, v in result.items()
                              if isinstance(v, (int, float)) and k != "insights_text"}
                if len(chart_data) >= 2:
                    import pandas as _pd
                    chart_df = _pd.DataFrame(
                        list(chart_data.items()), columns=["Metric", "Value"]
                    )
                    chart_result = build_chart_from_df(chart_df, question)
                    if chart_result:
                        state["chart_data"]    = chart_result["chart_json"]
                        state["table_data"]    = chart_result["table_rows"]
                        state["chart_insight"] = chart_result["insight"]
        except Exception:
            pass  # chart is optional — never break the answer

    except Exception as e:
        log.error("Error in Analytics Agent pipeline: %s", e)
        state["error"] = str(e)
        state["business_summary"] = f"An error occurred while running {module_name}."

    return state
